server:
  port: 9003
  servlet:
    context-path: /file
spring:
  application:
    name: file
  servlet:
    multipart:
      max-file-size: 50MB #单个文件的大小
      max-request-size: 50MB #请求的大小
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
file:
  path: /Users/zengmingqi/Pictures/
  domain: http://127.0.0.1:9000/file/f/