server:
  port: 9000
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: system
          uri: lb://system
          predicates:
            - Path=/system/**
        - id: business
          uri: lb://business
          predicates:
            - Path=/business/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka