server:
  port: 9000
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: system
          uri: http://127.0.0.1:9001
          predicates:
            - Path=/system/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka