server:
  port: 9000
spring:
  application:
    name: gateway
  redis:
    password: redis
    database: 1
  cloud:
    gateway:
      routes:
        - id: system
          uri: lb://system
          predicates:
            - Path=/system/**
          filters:
            - LoginAdmin
        - id: business
          uri: lb://business
          predicates:
            - Path=/business/**
          filters:
            - LoginAdmin
        - id: file
          uri: lb://file
          predicates:
            - Path=/file/**
          filters:
            - LoginAdmin
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka